CREATE DATABASE CONTROLEDESPESAS;

USE CONTROLEDESPESAS;

CREATE TABLE ESTADOS (
	IDESTADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ESTADO VARCHAR(200) NOT NULL,
    SIGLA CHAR(2) NOT NULL
);

CREATE TABLE CIDADES (
	IDCIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CIDADE VARCHAR(200) NOT NULL,
    IDESTADO INT NOT NULL,
    FOREIGN KEY (IDESTADO) REFERENCES ESTADOS(IDESTADO)
);

CREATE TABLE PESSOAS (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    DOCUMENTO VARCHAR(15),
    INSCRICAOESTADUAL VARCHAR(10),
    CEP VARCHAR(9),
    ENDERECO VARCHAR(200),
    BAIRRO VARCHAR(200),
    NUMERO INT,
    COMPLEMENTO VARCHAR(200),
    IDCIDADE INT,
    FOREIGN KEY (IDCIDADE) REFERENCES CIDADES(IDCIDADE),
    TELEFONE VARCHAR(10),
    EMAIL VARCHAR(200)
);

CREATE TABLE GRUPOSFLUXO (
	IDGRUPOFLUXO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    GRUPOFLUXO VARCHAR(200) NOT NULL
);

CREATE TABLE FORMASPAGAMENTO (
	IDFORMAPAGAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FORMAPAGAMENTO VARCHAR(200) NOT NULL
);

CREATE TABLE DESPESAS (
	IDDESPESA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    OBSERVACOES VARCHAR(255) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    DATACOMPRA DATE,
    DATAVENCIMENTO DATE,
    PARCELAS INT,
    IDFORMAPAGAMENTO INT,
    IDGRUPOFLUXO INT,
    IDPESSOA INT,
    FOREIGN KEY (IDFORMAPAGAMENTO) REFERENCES FORMASPAGAMENTO(IDFORMAPAGAMENTO),
    FOREIGN KEY (IDGRUPOFLUXO) REFERENCES GRUPOSFLUXO(IDGRUPOFLUXO),
    FOREIGN KEY (IDPESSOA) REFERENCES PESSOAS(IDPESSOA)
);

INSERT INTO FORMASPAGAMENTO (FORMAPAGAMENTO) VALUES ("Dinheiro");
INSERT INTO FORMASPAGAMENTO (FORMAPAGAMENTO) VALUES ("Cartão de Crédito");
INSERT INTO FORMASPAGAMENTO (FORMAPAGAMENTO) VALUES ("Cartão de Débito");
INSERT INTO FORMASPAGAMENTO (FORMAPAGAMENTO) VALUES ("PIX");
INSERT INTO FORMASPAGAMENTO (FORMAPAGAMENTO) VALUES ("Boleto");
