CREATE DATABASE CONTROLEDESPESAS;

USE CONTROLEDESPESAS;

CREATE TABLE PESSOAS (
	IDPESSOA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    TIPOPESSOA INT NOT NULL DEFAULT(0)
);

CREATE TABLE CATEGORIAS (
	IDCATEGORIA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CATEGORIA VARCHAR(200) NOT NULL
);

CREATE TABLE ESTADOS (
	IDESTADO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    ESTADO VARCHAR(200) NOT NULL,
    SIGLA CHAR(2) NOT NULL
);

CREATE TABLE CIDADES (
	IDCIDADE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CIDADE VARCHAR(200) NOT NULL,
    IDESTADO INT NOT NULL,
    FOREIGN KEY (IDESTADO) REFERENCES ESTADOS(IDESTADO)
);

CREATE TABLE EMPRESAS (
	IDEMPRESA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EMPRESA VARCHAR(200) NOT NULL
);

CREATE TABLE CAMINHOES (
	IDCAMINHAO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CAMINHAO VARCHAR(200) NOT NULL
);

CREATE TABLE EQUIPAMENTOS (
	IDEQUIPAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    EQUIPAMENTO VARCHAR(200) NOT NULL
);

CREATE TABLE CARREGADEIRAS (
	IDCARREGADEIRA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CARREGADEIRA VARCHAR(200)
);

CREATE TABLE FORMASPAGAMENTO (
	IDFORMAPAGAMENTO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    FORMAPAGAMENTO VARCHAR(200) NOT NULL
);

CREATE TABLE DESPESAS (
	IDDESPESA INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(255) NOT NULL,
    VALOR DECIMAL(10, 2) NOT NULL,
    DATACOMPRA DATE,
    DATAVENCIMENTO DATE,
    PARCELAS INT,
    IDFORMAPAGAMENTO INT,
    IDCATEGORIA INT,
    IDEMPRESA INT,
    IDPESSOA INT,
    IDCAMINHAO INT,
    IDEQUIPAMENTO INT,
    IDCARREGADEIRA INT,
    FOREIGN KEY (IDFORMAPAGAMENTO) REFERENCES FORMASPAGAMENTO(IDFORMAPAGAMENTO),
    FOREIGN KEY (IDCATEGORIA) REFERENCES CATEGORIAS(IDCATEGORIA),
    FOREIGN KEY (IDEMPRESA) REFERENCES EMPRESAS(IDEMPRESA),
    FOREIGN KEY (IDPESSOA) REFERENCES PESSOAS(IDPESSOA),
    FOREIGN KEY (IDCAMINHAO) REFERENCES CAMINHOES(IDCAMINHAO),
    FOREIGN KEY (IDEQUIPAMENTO) REFERENCES EQUIPAMENTOS(IDEQUIPAMENTO),
    FOREIGN KEY (IDCARREGADEIRA) REFERENCES CARREGADEIRAS(IDCARREGADEIRA)
);
